name: run
run_id: commands[0]
env TERM: xterm-256color
env TMPDIR: /var/folders/d_/fmwppt2s6zdd3hc8y4fvs_km0000gn/T/
env LANG: en_US.UTF-8
env HOME: /Users/albertmends
env PATH: /Users/albertmends/Documents/ecoair/backend/.tox/test_app/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/albertmends/.nvm/versions/node/v21.2.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
env PYTHONHASHSEED: 2964986003
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /Users/albertmends/Documents/ecoair/backend/.tox
env TOX_ENV_DIR: /Users/albertmends/Documents/ecoair/backend/.tox/test_app
env VIRTUAL_ENV: /Users/albertmends/Documents/ecoair/backend/.tox/test_app
env COLUMNS: 41
env LINES: 10
metadata pid: 34101
cwd: /Users/albertmends/Documents/ecoair/backend
allow: /Users/albertmends/Documents/ecoair/backend/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: -9
[32mINFO[0m:     ::1:56476 - "[1mGET /api/v1/instruments/get-instruments HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:56474 - "[1mGET /api/v1/manufacturers/get-manufacturers HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:56472 - "[1mGET /api/v1/parameters/get-parameters HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:56473 - "[1mGET /api/v1/countries/get-countries HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:56471 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:56475 - "[1mGET /api/v1/providers/get-providers HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:54476 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [91m500 Internal Server Error[0m
[32mINFO[0m:     ::1:54477 - "[1mGET /api/v1/parameters/get-parameters HTTP/1.1[0m" [91m500 Internal Server Error[0m

standard error:
[32m2024-03-31 18:23:37.224[0m | [33m[1mWARNING [0m | [36m__main__[0m:[36m<module>[0m:[36m60[0m - [33m[1mRunning in development mode. Do not run like this in production.[0m
[32mINFO[0m:     Started server process [[36m34101[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8001[0m (Press CTRL+C to quit)
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/app/api/endpoints/gLocations.py", line 14, in get_all_locations
    db = await get_database()
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/app/db/database.py", line 5, in get_database
    client = AsyncIOMotorClient(settings.mongo_details)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/motor/core.py", line 163, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/mongo_client.py", line 771, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 131, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 111, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 105, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.233 seconds: Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/app/api/endpoints/gParameters.py", line 14, in get_all_parameters
    db = await get_database()
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/app/db/database.py", line 5, in get_database
    client = AsyncIOMotorClient(settings.mongo_details)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/motor/core.py", line 163, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/mongo_client.py", line 771, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/uri_parser.py", line 558, in parse_uri
    nodes = dns_resolver.get_hosts()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 131, in get_hosts
    _, nodes = self._get_srv_response_and_hosts(True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 111, in _get_srv_response_and_hosts
    results = self._resolve_uri(encapsulate_errors)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/pymongo/srv_resolver.py", line 105, in _resolve_uri
    raise ConfigurationError(str(exc)) from None
pymongo.errors.ConfigurationError: The resolution lifetime expired after 21.177 seconds: Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.; Server Do53:172.20.10.1@53 answered The DNS operation timed out.
